language: node_js
sudo: false
node_js:
  - 12
  - 13
  - 14
  - 15
  - 16
install:
  # install Node.js dependencies
  - travis_retry npm ci
script:
  # run test suite
  - travis_retry npm test
after_success:
  # udpate coverate stats
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
